/**
 * Builds `{name}-app/index.ts` — the top-level re-export barrel for the
 * reactor package. Impl code imports from `'{name}-app'` instead of drilling
 * into `'{name}-app/document-models/<slug>/v1/gen/...'`.
 *
 * Each entry re-exports a document-model subfolder's `index.ts`, which in
 * turn re-exports the module object (`PhClintProject`, ...), action creators,
 * document/state types, and type guards. Fully machine-owned: regen on every
 * run.
 *
 * Powerhouse's own codegen might emit its own `index.ts` (as is the case for
 * ph-clint-app today, which has manifest/editors/processors re-exports). When
 * that exists, leave it alone — users hand-merge. Our codegen only emits when
 * the file is absent or was emitted by a previous ph-clint-cli run (hash
 * matches the ledger).
 */
import {
  type ClintProjectSpec,
  getDocumentTypeSlug,
} from '../../spec/types.js';

export function buildAppIndexTs(spec: ClintProjectSpec): string | null {
  if (!spec.features.powerhouse.enabled) return null;
  if (spec.documentTypes.length === 0) return null;

  const lines: string[] = [];
  lines.push('// THIS FILE IS GENERATED BY ph-clint-cli.');
  lines.push('// Re-exports every registered document model from a single top-level');
  lines.push('// entry so impl code can `import { ... } from \'{name}-app\'`.');
  lines.push('');
  for (const docType of spec.documentTypes) {
    const slug = getDocumentTypeSlug(docType);
    lines.push(`export * from './document-models/${slug}/index.js';`);
  }
  return lines.join('\n') + '\n';
}
