/**
 * Builds `{name}-app/index.ts` — the top-level re-export barrel for the
 * reactor package. Impl code imports from `'{name}-app'` instead of drilling
 * into `'{name}-app/document-models/<slug>/v1/gen/...'`.
 *
 * Only re-exports document types belonging to the app package (the project's
 * own reactor package). External packages' document types are imported from
 * their own npm packages, not from the app barrel.
 */
import {
  type ClintProjectSpec,
  getAppPackageName,
  getDocumentTypeSlug,
  isDocTypeGlob,
  phAtLeast,
} from '../../spec/types.js';

export function buildAppIndexTs(spec: ClintProjectSpec): string | null {
  if (!phAtLeast(spec.features.powerhouse, 'Reactor')) return null;

  const appPkg = getAppPackageName(spec);
  const appEntry = spec.packages.find((p) => p.packageName === appPkg);
  const docTypes = appEntry?.documentTypes ?? [];
  if (docTypes.length === 0) return null;

  const hasGlobs = docTypes.some(isDocTypeGlob);
  const explicits = docTypes.filter((dt) => !isDocTypeGlob(dt));

  const lines: string[] = [];
  lines.push('// THIS FILE IS GENERATED BY ph-clint-cli.');
  lines.push('// Re-exports every registered document model from a single top-level');
  lines.push('// entry so impl code can `import { ... } from \'{name}-app\'`.');
  lines.push('');

  if (hasGlobs) {
    // Glob patterns can't enumerate slugs at codegen time — re-export
    // from the Powerhouse-generated barrel which already re-exports all
    // document models in the package.
    lines.push("export * from './document-models/index.js';");
  }

  // Explicit entries still get per-slug re-exports (they may point at
  // models not yet in the generated barrel during bootstrapping).
  for (const docType of explicits) {
    const slug = getDocumentTypeSlug(docType);
    lines.push(`export * from './document-models/${slug}/index.js';`);
  }

  return lines.join('\n') + '\n';
}
