/**
 * Builds `{name}-app/index.ts` — the top-level re-export barrel for the
 * reactor package. Impl code imports from `'{name}-app'` instead of drilling
 * into `'{name}-app/document-models/<slug>/v1/gen/...'`.
 *
 * Only re-exports document types belonging to the app package (the project's
 * own reactor package). External packages' document types are imported from
 * their own npm packages, not from the app barrel.
 */
import {
  type ClintProjectSpec,
  getAppPackageName,
  getDocumentTypeSlug,
  isDocTypeGlob,
  phAtLeast,
} from '../../spec/types.js';

export function buildAppIndexTs(spec: ClintProjectSpec): string | null {
  if (!phAtLeast(spec.features.powerhouse, 'Reactor')) return null;

  const lines: string[] = [];

  // Standard Powerhouse reactor-package barrel — matches what `ph init`
  // generates. Required by main.tsx (Connect) and cli.ts imports.
  lines.push('// THIS FILE IS GENERATED BY ph-clint-cli.');
  lines.push("import type { Manifest } from 'document-model';");
  lines.push("import manifestJson from './powerhouse.manifest.json' with { type: 'json' };");
  lines.push("export { documentModels } from './document-models/document-models.js';");
  lines.push("export { upgradeManifests } from './document-models/upgrade-manifests.js';");
  lines.push("export { editors } from './editors/editors.js';");
  lines.push("export { processorFactory } from './processors/factory.js';");
  lines.push('export const manifest: Manifest = manifestJson;');

  // Per-document-type re-exports so impl code can import from
  // '{name}-app' instead of drilling into deep paths.
  const appPkg = getAppPackageName(spec);
  const appEntry = spec.packages.find((p) => p.packageName === appPkg);
  const docTypes = appEntry?.documentTypes ?? [];

  if (docTypes.length > 0) {
    const hasGlobs = docTypes.some(isDocTypeGlob);
    const explicits = docTypes.filter((dt) => !isDocTypeGlob(dt));

    lines.push('');
    if (hasGlobs) {
      lines.push("export * from './document-models/index.js';");
    }
    for (const docType of explicits) {
      const slug = getDocumentTypeSlug(docType);
      lines.push(`export * from './document-models/${slug}/index.js';`);
    }
  }

  return lines.join('\n') + '\n';
}
