/**
 * Builds `src/cli.ts` — the defineCli() call with feature blocks guarded by
 * `@clint:begin`/`@clint:end` markers so the code generator can patch
 * specific regions on subsequent runs (delta mode — future phase).
 */
import { type ClintProjectSpec, getAppPackageName, phAtLeast } from '../../spec/types.js';

export function buildCliTs(spec: ClintProjectSpec): string {
  const { mastra, routine, powerhouse } = spec.features;
  const ph = powerhouse;
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * CLI definition.');
  lines.push(' *');
  lines.push(' * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end');
  lines.push(' * markers are rewritten by ph-clint when the project spec changes.');
  lines.push(' * Everything outside the markers is user-editable and preserved.');
  lines.push(' */');

  const needsRoot = phAtLeast(ph, 'Reactor') || mastra.enabled;

  lines.push('// @clint:begin imports');
  if (phAtLeast(ph, 'Reactor')) {
    lines.push(`import { defineCli, buildDefaultReactor } from '@powerhousedao/ph-clint';`);
  } else {
    lines.push(`import { defineCli } from '@powerhousedao/ph-clint';`);
  }
  if (needsRoot) {
    lines.push("import path from 'node:path';");
  }
  lines.push(`import { CLI_NAME, CLI_VERSION${needsRoot ? ', CLI_ROOT' : ''} } from './config.js';`);
  lines.push(`import { configSchema, secretsSchema } from './framework.js';`);
  if (phAtLeast(ph, 'Reactor')) {
    lines.push(`import { documentModels } from '${getAppPackageName(spec)}';`);
  }
  if (mastra.enabled) {
    lines.push(`import { createAgent } from './agents/agent.js';`);
  }
  lines.push('// @clint:end imports');
  lines.push('');

  lines.push('export const cli = defineCli({');
  lines.push('  name: CLI_NAME,');
  lines.push('  version: CLI_VERSION,');
  if (phAtLeast(ph, 'Reactor')) {
    lines.push('  root: CLI_ROOT,');
  }
  lines.push('  description: `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('  configSchema,');
  lines.push('  secretsSchema,');
  lines.push('');
  lines.push('  // @clint:begin commands');
  lines.push('  commands: [],');
  lines.push('  // @clint:end commands');
  lines.push('');
  lines.push('  // @clint:begin services');
  lines.push('  services: [],');
  lines.push('  // @clint:end services');
  lines.push('');
  lines.push('  // @clint:begin triggers');
  if (routine.enabled) {
    lines.push('  triggers: [],');
  } else {
    lines.push('  triggers: [],');
  }
  lines.push('  // @clint:end triggers');
  lines.push('');
  lines.push('  // @clint:begin prompts');
  lines.push('  prompts: {');
  if (mastra.enabled) {
    lines.push("    artifacts: [path.join(CLI_ROOT, 'gen', 'skills'), path.join(CLI_ROOT, 'dist', 'gen', 'skills')],");
  } else {
    lines.push('    artifacts: [],');
  }
  if (mastra.enabled && mastra.agentId) {
    lines.push('    agents: {');
    lines.push(`      '${mastra.agentId}': {`);
    if (mastra.profiles.length > 0) {
      lines.push(`        name: '${mastra.profiles[0].id}',`);
      lines.push('        sections: [');
      for (const p of mastra.profiles) {
        lines.push(`          '${p.id}.md',`);
      }
      lines.push('        ],');
    } else {
      lines.push("        name: 'AgentBase',");
      lines.push("        sections: ['AgentBase.md'],");
    }
    lines.push('        skills: [],');
    lines.push('      },');
    lines.push('    },');
  } else {
    lines.push('    agents: {},');
  }
  lines.push('    skills: {},');
  lines.push('  },');
  lines.push('  // @clint:end prompts');
  lines.push('');
  lines.push('  // @clint:begin events');
  lines.push('  events: {},');
  lines.push('  // @clint:end events');
  if (spec.deployment.serviceAnnouncement) {
    lines.push('');
    lines.push('  serviceAnnouncement: { enabled: true },');
  }
  lines.push('');
  lines.push('  // @clint:begin interactive');
  lines.push('  interactive: {');
  lines.push(`    welcome: ({ workdir }) =>`);
  lines.push('      [');
  lines.push('        `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('        `Workdir: ${workdir}`,');
  lines.push("        '',");
  if (mastra.enabled) {
    lines.push(
      "        'Type a message to talk to the agent, or /help for commands.',",
    );
  } else {
    lines.push("        'Type /help for commands.',");
  }
  lines.push("      ].join('\\n'),");
  lines.push('  },');
  lines.push('  // @clint:end interactive');
  lines.push('});');
  lines.push('');

  lines.push('// @clint:begin reactor');
  if (phAtLeast(ph, 'Reactor')) {
    lines.push('cli.configureReactor({');
    lines.push('  create: (ctx) =>');
    lines.push('    buildDefaultReactor(ctx, {');
    lines.push('      documentModels,');
    lines.push(`      drive: { name: '${spec.name}' },`);
    lines.push('    }),');
    lines.push(
      `  switchboard: { enabled: ${String(phAtLeast(ph, 'Switchboard'))} },`,
    );
    lines.push(
      `  connect: { enabled: ${String(phAtLeast(ph, 'Connect'))} },`,
    );
    lines.push('});');
  }
  lines.push('// @clint:end reactor');
  lines.push('');

  lines.push('// @clint:begin mastra');
  if (mastra.enabled) {
    lines.push('cli.configureAgent(createAgent);');
  }
  lines.push('// @clint:end mastra');

  return lines.join('\n') + '\n';
}
