/**
 * Builds `src/cli.ts` — the defineCli() call with feature blocks guarded by
 * `@clint:begin`/`@clint:end` markers so the code generator can patch
 * specific regions on subsequent runs (delta mode — future phase).
 */
import { type ClintProjectSpec } from '../../spec/types.js';

export function buildCliTs(spec: ClintProjectSpec): string {
  const { mastra, routine, powerhouse } = spec.features;
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * CLI definition.');
  lines.push(' *');
  lines.push(' * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end');
  lines.push(' * markers are rewritten by ph-clint when the project spec changes.');
  lines.push(' * Everything outside the markers is user-editable and preserved.');
  lines.push(' */');

  if (powerhouse.enabled) {
    lines.push(`import path from 'node:path';`);
    lines.push(`import { fileURLToPath } from 'node:url';`);
    lines.push(`import { defineCli, buildDefaultReactor } from '@powerhousedao/ph-clint';`);
  } else {
    lines.push(`import { defineCli } from '@powerhousedao/ph-clint';`);
  }
  lines.push(`import { CLI_NAME, CLI_VERSION } from './config.js';`);
  lines.push(`import { configSchema, secretsSchema } from './framework.js';`);
  lines.push('');

  lines.push('// @clint:begin imports');
  if (powerhouse.enabled) {
    lines.push(`import { documentModels } from '${spec.name}-app';`);
  }
  if (mastra.enabled) {
    lines.push(`import { createAgent } from './agents/agent.js';`);
  }
  lines.push('// @clint:end imports');
  lines.push('');

  if (powerhouse.enabled) {
    lines.push(`const __dirname = path.dirname(fileURLToPath(import.meta.url));`);
    lines.push(`const appDir = path.resolve(__dirname, '../../${spec.name}-app');`);
    lines.push('');
  }

  lines.push('export const cli = defineCli({');
  lines.push('  name: CLI_NAME,');
  lines.push('  version: CLI_VERSION,');
  lines.push('  description: `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('  configSchema,');
  lines.push('  secretsSchema,');
  lines.push('');
  lines.push('  // @clint:begin commands');
  lines.push('  commands: [],');
  lines.push('  // @clint:end commands');
  lines.push('');
  lines.push('  // @clint:begin services');
  lines.push('  services: [],');
  lines.push('  // @clint:end services');
  lines.push('');
  lines.push('  // @clint:begin triggers');
  if (routine.enabled) {
    lines.push('  triggers: [],');
  } else {
    lines.push('  triggers: [],');
  }
  lines.push('  // @clint:end triggers');
  lines.push('');
  lines.push('  // @clint:begin prompts');
  lines.push('  prompts: {');
  lines.push('    sources: [],');
  lines.push('    agents: {},');
  lines.push('    skills: {},');
  lines.push('  },');
  lines.push('  // @clint:end prompts');
  lines.push('');
  lines.push('  // @clint:begin events');
  lines.push('  events: {},');
  lines.push('  // @clint:end events');
  lines.push('');
  lines.push('  // @clint:begin interactive');
  lines.push('  interactive: {');
  lines.push(`    welcome: ({ workdir }) =>`);
  lines.push('      [');
  lines.push('        `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('        `Workdir: ${workdir}`,');
  lines.push("        '',");
  if (mastra.enabled) {
    lines.push(
      "        'Type a message to talk to the agent, or /help for commands.',",
    );
  } else {
    lines.push("        'Type /help for commands.',");
  }
  lines.push("      ].join('\\n'),");
  lines.push('  },');
  lines.push('  // @clint:end interactive');
  lines.push('});');
  lines.push('');

  lines.push('// @clint:begin reactor');
  if (powerhouse.enabled) {
    lines.push('cli.configureReactor({');
    lines.push('  create: (ctx) =>');
    lines.push('    buildDefaultReactor(ctx, {');
    lines.push('      documentModels,');
    lines.push(`      drive: { name: '${spec.name}' },`);
    lines.push('    }),');
    lines.push(
      `  switchboard: { enabled: ${String(powerhouse.switchboard)} },`,
    );
    lines.push(
      `  connect: { enabled: ${String(powerhouse.connect)}, workdir: appDir },`,
    );
    lines.push('});');
  }
  lines.push('// @clint:end reactor');
  lines.push('');

  lines.push('// @clint:begin mastra');
  if (mastra.enabled) {
    lines.push('cli.configureAgent(createAgent);');
  }
  lines.push('// @clint:end mastra');

  return lines.join('\n') + '\n';
}
