/**
 * Builds `src/framework.gen.ts` — the fully machine-owned half of the
 * typed-binding split. Regenerated on every `init` and `update`; holds the
 * `defineRegistry([...] as const)` call that describes which document models
 * are bound into `framework.ts`'s typed factories.
 *
 * Iterates all packages' document types. The app package's modules are
 * imported from the local `{name}-app` package; external packages' modules
 * are imported from their npm package name.
 *
 * Emitted only when Powerhouse is enabled — flat-layout impls have no
 * reactor package to import modules from and bind `createTypes` directly in
 * `framework.ts`. When Powerhouse is on but no document types are declared,
 * we still emit this file with an empty `defineRegistry([])` so impl code's
 * `import { registry } from './framework.gen.js'` keeps resolving across
 * regens.
 */
import {
  type ClintProjectSpec,
  getAppPackageName,
  getDocumentTypeModuleName,
  phAtLeast,
} from '../../spec/types.js';

export function buildFrameworkGenTs(spec: ClintProjectSpec): string | null {
  if (!phAtLeast(spec.features.powerhouse, 'Reactor')) return null;

  const appPkg = getAppPackageName(spec);

  // Collect all (docType, moduleName, importFrom) tuples across packages.
  const entries: { docType: string; name: string; importFrom: string }[] = [];
  for (const pkg of spec.packages) {
    const importFrom = pkg.packageName === appPkg ? appPkg : pkg.packageName;
    for (const docType of pkg.documentTypes) {
      entries.push({
        docType,
        name: getDocumentTypeModuleName(docType),
        importFrom,
      });
    }
  }

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * THIS FILE IS GENERATED BY ph-clint-cli. DO NOT EDIT.');
  lines.push(' *');
  lines.push(' * Regenerated on every `ph-clint clint-project-regen` and on every spec-change');
  lines.push(' * tick. Put custom bindings in `framework.ts`, not here — edits to');
  lines.push(' * this file will be overwritten.');
  lines.push(' */');
  lines.push(`import { defineRegistry } from '@powerhousedao/ph-clint';`);
  for (const e of entries) {
    lines.push(`import { ${e.name} } from '${e.importFrom}';`);
  }
  lines.push('');
  lines.push('/**');
  lines.push(' * Typed document registry derived from the reactor package\'s document models.');
  lines.push(' * Regenerated whenever the spec\'s packages or document types change.');
  lines.push(' */');
  if (entries.length === 0) {
    lines.push('export const registry = defineRegistry([] as const);');
  } else {
    lines.push('export const registry = defineRegistry([');
    for (const e of entries) {
      lines.push(`  ${e.name},`);
    }
    lines.push('] as const);');
  }
  lines.push('');
  lines.push('export type Registry = typeof registry;');
  return lines.join('\n') + '\n';
}
