/**
 * Builds `src/framework.gen.ts` — the fully machine-owned half of the
 * typed-binding split. Regenerated on every `init` and `update`; holds the
 * `defineRegistry([...] as const)` call that describes which document models
 * are bound into `framework.ts`'s typed factories.
 *
 * Kept deliberately small: this file exports only `registry` and the
 * `Registry` type. The `createTypes` call lives in `framework.ts` (the
 * user-owned half) so `configSchema` edits stay local and we avoid an import
 * cycle between the two files.
 *
 * Emitted only when Powerhouse is enabled — flat-layout impls have no
 * reactor package to import modules from and bind `createTypes` directly in
 * `framework.ts`. When Powerhouse is on but no `documentTypes` are declared,
 * we still emit this file with an empty `defineRegistry([])` so impl code's
 * `import { registry } from './framework.gen.js'` keeps resolving across
 * regens.
 */
import {
  type ClintProjectSpec,
  getDocumentTypeModuleName,
} from '../../spec/types.js';

/** Local package name of the reactor package for this project. */
function appPackageName(spec: ClintProjectSpec): string {
  return `${spec.name}-app`;
}

export function buildFrameworkGenTs(spec: ClintProjectSpec): string | null {
  if (!spec.features.powerhouse.enabled) return null;

  const pkg = appPackageName(spec);
  const entries = spec.documentTypes.map((docType) => ({
    docType,
    name: getDocumentTypeModuleName(docType),
  }));

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * THIS FILE IS GENERATED BY ph-clint-cli. DO NOT EDIT.');
  lines.push(' *');
  lines.push(' * Regenerated on every `ph-clint clint-project-regen` and on every spec-change');
  lines.push(' * tick. Put custom bindings in `framework.ts`, not here — edits to');
  lines.push(' * this file will be overwritten.');
  lines.push(' */');
  lines.push(`import { defineRegistry } from '@powerhousedao/ph-clint';`);
  for (const e of entries) {
    lines.push(`import { ${e.name} } from '${pkg}';`);
  }
  lines.push('');
  lines.push('/**');
  lines.push(' * Typed document registry derived from the reactor package\'s document models.');
  lines.push(' * Regenerated whenever the spec\'s `documentTypes` list changes.');
  lines.push(' */');
  if (entries.length === 0) {
    lines.push('export const registry = defineRegistry([] as const);');
  } else {
    lines.push('export const registry = defineRegistry([');
    for (const e of entries) {
      lines.push(`  ${e.name},`);
    }
    lines.push('] as const);');
  }
  lines.push('');
  lines.push('export type Registry = typeof registry;');
  return lines.join('\n') + '\n';
}
