import fs from 'node:fs';
import path from 'node:path';
import { renderSkillTemplate } from 'ph-clint';
import type { BuildConfig } from './types.js';

/**
 * Build agent profile instructions by rendering base+specialized template pairs.
 * Writes a TypeScript file exporting each profile as a `const` string.
 *
 * @returns Number of profiles built and any warnings.
 */
export function buildAgentProfiles(config: BuildConfig): { count: number; warnings: string[] } {
  const log = config.logger ?? console.log;
  const profiles = config.agentProfiles ?? [];
  if (profiles.length === 0) return { count: 0, warnings: [] };

  const profilesDir = path.join(
    config.promptsDir ?? path.join(config.projectRoot, 'prompts'),
    config.subdirs?.profiles ?? 'agent-profiles',
  );
  const outputDir = config.outputGeneratedDir ?? path.join(config.projectRoot, 'src', 'generated');

  log('\n--- Building agent instructions ---');

  const exports: string[] = [];
  const allWarnings: string[] = [];
  let count = 0;

  for (const profile of profiles) {
    const basePath = path.join(profilesDir, profile.baseTemplate);
    const specPath = path.join(profilesDir, profile.specializedTemplate);

    if (!fs.existsSync(basePath) || !fs.existsSync(specPath)) {
      log(`  SKIP ${profile.name}: missing template files`);
      continue;
    }

    const baseRaw = fs.readFileSync(basePath, 'utf-8');
    const specRaw = fs.readFileSync(specPath, 'utf-8');

    const agentContext = { ...config.context, agentName: profile.name };
    const renderOpts = config.customHelpers ? { helpers: config.customHelpers } : undefined;

    const baseResult = renderSkillTemplate(baseRaw, agentContext, renderOpts);
    const specResult = renderSkillTemplate(specRaw, agentContext, renderOpts);

    for (const w of baseResult.warnings) {
      const msg = `${profile.name}/${profile.baseTemplate}: ${w}`;
      allWarnings.push(msg);
      log(`  WARN ${msg}`);
    }
    for (const w of specResult.warnings) {
      const msg = `${profile.name}/${profile.specializedTemplate}: ${w}`;
      allWarnings.push(msg);
      log(`  WARN ${msg}`);
    }

    const combined = baseResult.rendered.trim() + '\n\n' + specResult.rendered.trim() + '\n';

    const varName = profile.name.charAt(0).toLowerCase() + profile.name.slice(1) + 'Instructions';
    exports.push(`export const ${varName} = ${JSON.stringify(combined)};\n`);

    log(`  OK ${profile.name} → ${varName} (${combined.length} chars)`);
    count++;
  }

  if (exports.length > 0) {
    const outputPath = path.join(outputDir, 'agent-instructions.ts');
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(
      outputPath,
      `// Auto-generated by ph-clint-dev build-skills — do not edit.\n\n${exports.join('\n')}\n`,
      'utf-8',
    );
    log(`  Written to ${path.relative(config.projectRoot, outputPath)}`);
  }

  return { count, warnings: allWarnings };
}
