import fs from 'node:fs';
import path from 'node:path';
import { renderSkillTemplate } from 'ph-clint';
import type { BuildConfig } from './types.js';

/**
 * Build agent profile instructions by rendering base+specialized template pairs.
 * Writes a TypeScript file exporting each profile as a `const` string.
 *
 * @returns Number of profiles built and any warnings.
 */
export function buildAgentProfiles(config: BuildConfig): { count: number; warnings: string[] } {
  const log = config.logger ?? console.log;
  const profiles = config.agentProfiles ?? [];
  if (profiles.length === 0) return { count: 0, warnings: [] };

  const profilesDir = path.join(
    config.promptsDir ?? path.join(config.projectRoot, 'prompts'),
    config.subdirs?.profiles ?? 'agent-profiles',
  );
  const outputDir = config.outputGeneratedDir ?? path.join(config.projectRoot, 'src', 'generated');

  log('\n--- Building agent instructions ---');

  const exports: string[] = [];
  const allWarnings: string[] = [];
  let count = 0;

  for (const profile of profiles) {
    // Check all section files exist before rendering
    let missing = false;
    for (const section of profile.sections) {
      if (!fs.existsSync(path.join(profilesDir, section))) {
        log(`  SKIP ${profile.name}: missing section ${section}`);
        missing = true;
        break;
      }
    }
    if (missing) continue;

    const agentContext = { ...config.context, agentName: profile.name };
    const renderOpts = config.customHelpers ? { helpers: config.customHelpers } : undefined;

    const renderedSections: string[] = [];
    for (const section of profile.sections) {
      const raw = fs.readFileSync(path.join(profilesDir, section), 'utf-8');
      const result = renderSkillTemplate(raw, agentContext, renderOpts);
      for (const w of result.warnings) {
        const msg = `${profile.name}/${section}: ${w}`;
        allWarnings.push(msg);
        log(`  WARN ${msg}`);
      }
      renderedSections.push(result.rendered.trim());
    }

    const combined = renderedSections.join('\n\n') + '\n';

    const varName = profile.name.charAt(0).toLowerCase() + profile.name.slice(1) + 'Instructions';
    exports.push(`export const ${varName} = ${JSON.stringify(combined)};\n`);

    log(`  OK ${profile.name} → ${varName} (${combined.length} chars)`);
    count++;
  }

  if (exports.length > 0) {
    const outputPath = path.join(outputDir, 'agent-instructions.ts');
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(
      outputPath,
      `// Auto-generated by ph-clint-dev build-skills — do not edit.\n\n${exports.join('\n')}\n`,
      'utf-8',
    );
    log(`  Written to ${path.relative(config.projectRoot, outputPath)}`);
  }

  return { count, warnings: allWarnings };
}
