/**
 * THIS FILE IS GENERATED BY ph-clint-cli. DO NOT EDIT.
 *
 * Regenerated on every `ph-clint clint-project-regen` and on every spec-change tick.
 * Put custom bindings in `framework.ts`, not here — edits to this file
 * will be overwritten.
 */
import { defineRegistry } from '@powerhousedao/ph-clint';
import { PhClintProject } from '@powerhousedao/ph-clint-app';

/**
 * Typed document registry derived from the reactor package's document models.
 * Regenerated whenever the spec's `documentTypes` list changes.
 */
export const registry = defineRegistry([
  PhClintProject,
] as const);

export type Registry = typeof registry;
