/**
 * Per-CLI typed framework binding.
 *
 * This file binds ph-clint's `configSchema` and `registry` generics once
 * and re-exports pre-typed `defineCommand` / `defineTrigger` / `defineService`
 * factories. Every command, trigger, and service in this CLI should import
 * these definers from here (not from `ph-clint`) so call sites don't have to
 * repeat the generics.
 *
 * Phase 4 note: this file will be regenerated by ph-clint-cli codegen.
 */
import { createTypes } from 'ph-clint';
import type { RegistryEntry } from 'ph-clint';
import { documentModels } from 'ph-clint-app';
import type {
  PhClintProjectAction,
  PhClintProjectPHState,
} from 'ph-clint-app/document-models/ph-clint-project';
import { configSchema, secretsSchema } from './config.js';
import { z } from 'zod';

/**
 * DocumentRegistry for this CLI. One entry per registered document model.
 * The runtime value is populated from `documentModels` via `documentType` →
 * module; the type is hand-written so `reactor.client.get<T>(...)` narrows
 * to the concrete PhClintProjectDocument shape. Phase 4's codegen will
 * derive both from the generated module tuple.
 */
export type Registry = {
  'powerhouse/ph-clint-project': RegistryEntry<
    PhClintProjectPHState,
    PhClintProjectAction
  >;
};

export const registry = Object.fromEntries(
  documentModels.map((m) => [m.documentModel.global.id, m]),
) as unknown as Registry;

/** Merged config + secrets schema — drives TConfig through the typed bindings. */
export const fullConfigSchema = configSchema.merge(secretsSchema);
export type Config = z.infer<typeof fullConfigSchema>;

export const { defineCommand, defineTrigger, defineService } = createTypes({
  configSchema: fullConfigSchema,
  registry,
});
