/**
 * Builds `src/cli.ts` — the defineCli() call with feature blocks guarded by
 * `@clint:begin`/`@clint:end` markers so the code generator can patch
 * specific regions on subsequent runs (delta mode — future phase).
 */
import { type ClintProjectSpec, getAppPackageName, phAtLeast } from '../../spec/types.js';

/** External packages that have document types (not the app package). */
function getExternalPackages(spec: ClintProjectSpec) {
  const appPkg = getAppPackageName(spec);
  return spec.packages.filter(
    (p) => p.packageName !== appPkg && p.documentTypes.length > 0,
  );
}

export function buildCliTs(spec: ClintProjectSpec): string {
  const { mastra, routine, powerhouse } = spec.features;
  const observabilityEnabled = spec.deployment.observabilityEnabled;
  const ph = powerhouse;
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * CLI definition.');
  lines.push(' *');
  lines.push(' * Generated by ph-clint. Regions bracketed by @clint:begin/@clint:end');
  lines.push(' * markers are rewritten by ph-clint when the project spec changes.');
  lines.push(' * Everything outside the markers is user-editable and preserved.');
  lines.push(' */');

  const needsRoot = phAtLeast(ph, 'Reactor') || mastra.enabled;

  lines.push('// @clint:begin imports');
  const phClintImports = ['defineCli'];
  if (phAtLeast(ph, 'Reactor')) phClintImports.push('buildDefaultReactor');
  // proxy has no additional imports
  lines.push(`import { ${phClintImports.join(', ')} } from '@powerhousedao/ph-clint';`);
  if (needsRoot) {
    lines.push("import path from 'node:path';");
  }
  lines.push(`import { CLI_NAME, CLI_VERSION${needsRoot ? ', CLI_ROOT' : ''} } from './config.js';`);
  lines.push(`import { configSchema, secretsSchema } from './framework.js';`);
  if (phAtLeast(ph, 'Reactor')) {
    lines.push(`import { documentModels } from '${getAppPackageName(spec)}';`);
    const extPkgs = getExternalPackages(spec);
    for (let i = 0; i < extPkgs.length; i++) {
      const alias = extPkgs.length === 1 ? 'extModels' : `extModels${i}`;
      lines.push(`import { documentModels as ${alias} } from '${extPkgs[i].packageName}';`);
    }
  }
  if (mastra.enabled) {
    lines.push(`import { createAgent } from './agents/agent.js';`);
  }
  if (mastra.enabled && mastra.common?.enableChat) {
    lines.push(`import { chatSessionWatchTrigger } from '@powerhousedao/clint-common/chat';`);
  }
  if (observabilityEnabled) {
    lines.push(`import { observability } from '@powerhousedao/ph-clint-observability';`);
  }
  lines.push('// @clint:end imports');
  lines.push('');

  lines.push('export const cli = defineCli({');
  lines.push('  name: CLI_NAME,');
  lines.push('  version: CLI_VERSION,');
  lines.push('  // @clint:begin root');
  if (phAtLeast(ph, 'Reactor')) {
    lines.push('  root: CLI_ROOT,');
  }
  lines.push('  // @clint:end root');
  lines.push('  description: `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('  configSchema,');
  lines.push('  secretsSchema,');
  lines.push('');
  lines.push('  // @clint:begin commands');
  lines.push('  commands: [],');
  lines.push('  // @clint:end commands');
  lines.push('');
  lines.push('  // @clint:begin services');
  lines.push('  services: [],');
  lines.push('  // @clint:end services');
  lines.push('');
  lines.push('  // @clint:begin triggers');
  if (mastra.enabled && mastra.common?.enableChat) {
    lines.push('  triggers: [chatSessionWatchTrigger],');
  } else {
    lines.push('  triggers: [],');
  }
  lines.push('  // @clint:end triggers');
  lines.push('');
  lines.push('  // @clint:begin prompts');
  lines.push('  prompts: {');
  if (mastra.enabled) {
    lines.push("    artifacts: [path.join(CLI_ROOT, 'gen', 'skills'), path.join(CLI_ROOT, 'dist', 'gen', 'skills')],");
  } else {
    lines.push('    artifacts: [],');
  }
  if (mastra.enabled && mastra.mainAgent) {
    lines.push('    agents: {');
    const allAgents: { id: string; profileIds: string[]; skills: string[] }[] = [
      {
        id: mastra.mainAgent.id,
        profileIds: mastra.mainAgent.profileIds,
        skills: mastra.mainAgent.skills,
      },
      ...mastra.subAgents.map((s) => ({
        id: s.id,
        profileIds: s.profileIds,
        skills: s.skills,
      })),
    ];
    // Fall back to the first available profile when an agent has none
    // assigned. The `AgentBase.md` builder only emits when `profiles[]` is
    // empty, so referencing it from a non-empty-profile spec would be a dead
    // link. With a non-empty library, the first profile is the safest default
    // an agent always has at least one instruction file at build time.
    const fallbackSection =
      mastra.profiles.length > 0
        ? `'${mastra.profiles[0].id}.md'`
        : "'AgentBase.md'";
    for (const a of allAgents) {
      lines.push(`      '${a.id}': {`);
      lines.push(`        name: '${a.id}',`);
      const sections =
        a.profileIds.length > 0
          ? a.profileIds.map((id) => `'${id}.md'`)
          : [fallbackSection];
      lines.push(`        sections: [${sections.join(', ')}],`);
      const skills = a.skills.map((s) => `'${s}'`).join(', ');
      lines.push(`        skills: [${skills}],`);
      lines.push('      },');
    }
    lines.push('    },');
  } else {
    lines.push('    agents: {},');
  }
  lines.push('    skills: {},');
  lines.push('  },');
  lines.push('  // @clint:end prompts');
  lines.push('');
  lines.push('  // @clint:begin events');
  lines.push('  events: {},');
  lines.push('  // @clint:end events');
  lines.push('');
  lines.push('  // @clint:begin proxy');
  if (spec.deployment.proxyEnabled) {
    lines.push('  proxyEnabled: true,');
  }
  lines.push('  // @clint:end proxy');
  lines.push('');
  lines.push('  // @clint:begin lifecycle');
  if (observabilityEnabled) {
    lines.push('  lifecycle: [observability()],');
  }
  lines.push('  // @clint:end lifecycle');
  lines.push('');
  lines.push('  // @clint:begin interactive');
  lines.push('  interactive: {');
  lines.push(`    welcome: ({ workdir }) =>`);
  lines.push('      [');
  lines.push('        `${CLI_NAME} v${CLI_VERSION}`,');
  lines.push('        `Workdir: ${workdir}`,');
  lines.push("        '',");
  if (mastra.enabled) {
    lines.push(
      "        'Type a message to talk to the agent, or / for commands.',",
    );
  } else {
    lines.push("        'Type / for commands or /cli-docs for help.',");
  }
  lines.push("      ].join('\\n'),");
  lines.push('  },');
  lines.push('  // @clint:end interactive');
  lines.push('});');
  lines.push('');

  lines.push('// @clint:begin reactor');
  if (phAtLeast(ph, 'Reactor')) {
    lines.push('cli.configureReactor({');
    lines.push('  create: (ctx) =>');
    lines.push('    buildDefaultReactor(ctx, {');
    const extPkgs = getExternalPackages(spec);
    // Spread even when there are no external packages: ph init now emits
    // `documentModels = [] as const` (readonly []), and passing that bare
    // to a `DocumentModelModule[]` parameter trips TS4104. Spreading
    // materializes a fresh mutable array.
    if (extPkgs.length === 0) {
      lines.push('      documentModels: [...documentModels],');
    } else {
      const aliases = extPkgs.map((_, i) => extPkgs.length === 1 ? 'extModels' : `extModels${i}`);
      lines.push(`      documentModels: [...documentModels, ${aliases.map(a => `...${a}`).join(', ')}],`);
    }
    lines.push(`      drive: { name: '${spec.name}' },`);
    lines.push('      subscriptions: {},');
    lines.push('    }),');
    lines.push(
      `  switchboard: { enabled: ${String(phAtLeast(ph, 'Switchboard'))} },`,
    );
    lines.push(
      `  connect: { enabled: ${String(phAtLeast(ph, 'Connect'))} },`,
    );
    lines.push('});');
  }
  lines.push('// @clint:end reactor');
  lines.push('');

  lines.push('// @clint:begin mastra');
  if (mastra.enabled) {
    lines.push('cli.configureAgent(createAgent);');
  }
  lines.push('// @clint:end mastra');

  return lines.join('\n') + '\n';
}
