/**
 * Builds `src/framework.gen.ts` — the fully machine-owned half of the
 * typed-binding split. Regenerated on every `init` and `update`; holds the
 * `defineRegistry([...])` call that describes which document models
 * are bound into `framework.ts`'s typed factories.
 *
 * Iterates all packages' document types. The app package's modules are
 * imported from the local `{name}-app` package; external packages' modules
 * are imported from their npm package name.
 *
 * Document type entries may be explicit IDs (`powerhouse/ph-clint-project`)
 * or glob patterns (`*​/*`, `powerhouse/*`, `acme/doc-*`).  Explicit IDs
 * produce static named imports; glob patterns import the package's
 * `documentModels` array and filter at runtime so newly-added document
 * models are picked up without a codegen re-run.
 *
 * Emitted only when Powerhouse is enabled — flat-layout impls have no
 * reactor package to import modules from and bind `createTypes` directly in
 * `framework.ts`. When Powerhouse is on but no document types are declared,
 * we still emit this file with an empty `defineRegistry([])` so impl code's
 * `import { registry } from './framework.gen.js'` keeps resolving across
 * regens.
 */
import {
  type ClintProjectSpec,
  docTypeGlobToRegex,
  getAppPackageName,
  getDocumentTypeModuleName,
  getDocumentTypeSlug,
  isDocTypeGlob,
  phAtLeast,
} from '../../spec/types.js';

/** A single named-import entry (explicit document type). */
interface ExplicitEntry {
  kind: 'explicit';
  name: string;
  importFrom: string;
}

/** A runtime-filtered entry (glob pattern on a package's documentModels). */
interface GlobEntry {
  kind: 'glob';
  /** Alias for the documentModels import (unique per package). */
  modelsAlias: string;
  importFrom: string;
  regexSource: string;
}

type RegistryEntry = ExplicitEntry | GlobEntry;

export function buildFrameworkGenTs(spec: ClintProjectSpec): string | null {
  if (!phAtLeast(spec.features.powerhouse, 'Reactor')) return null;

  const appPkg = getAppPackageName(spec);

  // Collect entries across packages. Each package may contribute both
  // explicit named imports and glob-based runtime filters.
  const entries: RegistryEntry[] = [];
  let globCounter = 0;

  for (const pkg of spec.packages) {
    const isApp = pkg.packageName === appPkg;

    // Collect glob patterns for this package (may be multiple).
    const globs = pkg.documentTypes.filter(isDocTypeGlob);
    const explicits = pkg.documentTypes.filter((dt) => !isDocTypeGlob(dt));

    for (const docType of explicits) {
      const slug = getDocumentTypeSlug(docType);
      entries.push({
        kind: 'explicit',
        name: getDocumentTypeModuleName(docType),
        importFrom: isApp ? appPkg : `${pkg.packageName}/document-models/${slug}`,
      });
    }

    if (globs.length > 0) {
      // Merge all globs for this package into a single regex alternation.
      const combined = globs.length === 1
        ? docTypeGlobToRegex(globs[0])
        : globs.map((g) => `(?:${docTypeGlobToRegex(g)})`).join('|');
      const alias = globCounter === 0 ? 'globModels' : `globModels${globCounter}`;
      globCounter++;
      entries.push({
        kind: 'glob',
        modelsAlias: alias,
        importFrom: isApp ? appPkg : pkg.packageName,
        regexSource: combined,
      });
    }
  }

  const hasGlobs = entries.some((e) => e.kind === 'glob');

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * THIS FILE IS GENERATED BY ph-clint-cli. DO NOT EDIT.');
  lines.push(' *');
  lines.push(' * Regenerated on every `ph-clint clint-project-regen` and on every spec-change');
  lines.push(' * tick. Put custom bindings in `framework.ts`, not here — edits to');
  lines.push(' * this file will be overwritten.');
  lines.push(' */');
  lines.push(`import { defineRegistry } from '@powerhousedao/ph-clint';`);
  // Glob entries widen each `documentModels` import to `readonly DocumentModelModule[]`
  // before filtering. Without this, a freshly-scaffolded reactor package whose
  // `documentModels` is exported as `[] as const` (no models defined yet) would
  // make the filter callback's `m` infer to `never`, and `m.documentModel.global.id`
  // would fail to type-check. The glob branch already abandons `as const` literal
  // narrowing, so widening to the base module type costs nothing extra.
  if (hasGlobs) {
    lines.push(`import type { DocumentModelModule } from 'document-model';`);
  }

  // Emit imports — named imports for explicit entries, documentModels for globs.
  for (const e of entries) {
    if (e.kind === 'explicit') {
      lines.push(`import { ${e.name} } from '${e.importFrom}';`);
    } else {
      lines.push(`import { documentModels as ${e.modelsAlias} } from '${e.importFrom}';`);
    }
  }

  lines.push('');
  lines.push('/**');
  lines.push(' * Typed document registry derived from the reactor package\'s document models.');
  lines.push(' * Regenerated whenever the spec\'s packages or document types change.');
  lines.push(' */');

  if (entries.length === 0) {
    lines.push('export const registry = defineRegistry([] as const);');
  } else if (!hasGlobs) {
    // Pure explicit — use `as const` for full type inference.
    lines.push('export const registry = defineRegistry([');
    for (const e of entries) {
      if (e.kind === 'explicit') {
        lines.push(`  ${e.name},`);
      }
    }
    lines.push('] as const);');
  } else {
    // Mix of explicit + glob — runtime filter loses `as const` inference.
    lines.push('export const registry = defineRegistry([');
    for (const e of entries) {
      if (e.kind === 'explicit') {
        lines.push(`  ${e.name},`);
      } else {
        lines.push(`  ...(${e.modelsAlias} as readonly DocumentModelModule[]).filter((m) => /${e.regexSource}/.test(m.documentModel.global.id)),`);
      }
    }
    lines.push(']);');
  }

  lines.push('');
  lines.push('export type Registry = typeof registry;');
  return lines.join('\n') + '\n';
}
